name: Publish Library

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: zulu
        cache: gradle
    - name: Gradle Wrapper Validation
      uses: gradle/wrapper-validation-action@v1
    - name: Gradle Build Action
      uses: gradle/gradle-build-action@v2
      with:
        arguments: |
          --stacktrace
          :api:build
          :plugin:build
          :mod:build
          :protocol:build
          :graffiti:build
          :graffiti-protocol:build
          :graffiti-service:build
          :protocol-serialization:build
          :protocol-mod:build
          :backport-artifact:build
          :api:publish
          :plugin:publish
          :mod:publish
          :protocol:publish
          :graffiti:publish
          :graffiti-protocol:build
          :graffiti-service:publish
          :protocol-serialization:publish
          :protocol-mod:publish
          :backport-artifact:publish
      env: 
        CRI_REPO_LOGIN: ${{ secrets.CRI_REPO_LOGIN }}
        CRI_REPO_PASSWORD: ${{ secrets.CRI_REPO_PASSWORD }}
